const messagesWeeklyChallenge: string[] = [
	"Seven days of note-taking? You're practically a note ninja turtle now! 🐢📝 [X] points, cowabunga!",
	"You've just completed a week-long note-taking marathon! 🏃‍♂️📝 [X] points earned. Ready for the next lap?",
	"A whole week of notes? You're on fire! 🔥📝 [X] points, keep the spark alive!",
	"Seven notes in seven days - that's like a note symphony! 🎶📝 [X] points, maestro!",
	"You're on a seven-day note-taking fiesta! 🎉📝 [X] points, keep the party going!",
	"Seven days, seven notes - You're like the James Bond of note-taking! 🕶️📝 [X] points, secret agent!",
	"You're officially a 'Note-A-Day' superhero! 🦸‍♂️📝 [X] points, capes optional!",
	"A whole week of notes? You've practically written a mini novel by now! 📚📝 [X] points, author status achieved!",
	"Seven days straight? You're the Usain Bolt of note-taking! 🏃‍♂️📝 [X] points, sprinting towards knowledge!",
	"You're on a seven-day note-taking spree! It's like a notes-plosion! 💥📝 [X] points, keep the fireworks coming!",
	"Seven days, seven notes - you're basically the Michael Jordan of note-taking! 🏀📝 [X] points, slam dunk!",
	"A whole week of notes? You're the note-taking MVP! 🏆📝 [X] points, keep scoring!",
	"You've just unlocked the 'Seven Day Note Fever' achievement! 🌟📝 [X] points, catch the fever!",
	"Seven days, seven notes - you're a note-taking rockstar! 🎸📝 [X] points, keep jammin'!",
	"You're on a seven-day note-taking magic show! Now you see the notes, now you don't! 🎩✨ [X] points, keep the magic alive!",
	"A whole week of notes? You're like a note-taking Jedi Master! 🌌⚔️ [X] points, may the notes be with you!",
	"Seven days straight? You're the Tony Hawk of note-taking! 🛹📝 [X] points, keep shredding!",
	"You're on a seven-day note-taking rollercoaster! Up and down, but always moving forward! 🎢📝 [X] points, enjoy the ride!",
	"Seven days, seven notes - you're a note-taking DJ spinning knowledge beats! 🎧📝 [X] points, drop the knowledge!",
	"You've just conquered the seven-day note-taking challenge! You're the note-taking Indiana Jones! 🏹📝 [X] points, keep exploring!",
	"A whole week of notes? You're the note-taking Sherlock Holmes, solving knowledge mysteries! 🔍📝 [X] points, keep sleuthing!",
	"Seven days, seven notes - you're a note-taking Picasso, creating a masterpiece of knowledge! 🎨📝 [X] points, keep painting!",
	"You're on a seven-day note-taking rocket ship! Destination: Infinite Knowledge! 🚀📝 [X] points, enjoy the journey!",
	"Seven days straight? You're the note-taking MacGyver, turning information into solutions! 🔧📝 [X] points, keep crafting!",
	"You're on a seven-day note-taking safari, exploring the wilds of knowledge! 🐘📝 [X] points, keep exploring!",
	"Seven days, seven notes - you're a note-taking chef, cooking up a knowledge feast! 🍳📝 [X] points, keep cooking!",
	"You've just unlocked the seven-day note-taking badge! You're the note-taking superhero we need! 🦸‍♀️📝 [X] points, keep saving the day!",
	"A whole week of notes? You're the note-taking Lewis and Clark, charting new territories of knowledge! 🗺️📝 [X] points, keep exploring!",
	"Seven days, seven notes - you're a note-taking DJ, dropping beats of wisdom! 🎧📝 [X] points, keep spinning!",
	"You're on a seven-day note-taking treasure hunt, discovering gems of wisdom! 💎📝 [X] points, keep hunting!",
	"Seven days straight? You're the note-taking ninja warrior, conquering the knowledge obstacle course! 🥋📝 [X] points, keep slaying!",
	"You're on a seven-day note-taking rocket ship! Destination: Infinite Knowledge! 🚀📝 [X] points, enjoy the journey!",
	"Seven days, seven notes - you're a note-taking detective, solving cases of curiosity! 🕵️‍♂️📝 [X] points, keep detecting!",
	"You've just unlocked the seven-day note-taking badge! You're the note-taking superhero we need! 🦸‍♂️📝 [X] points, keep saving the day!",
	"A whole week of notes? You're the note-taking pioneer, blazing trails through the forests of information! 🌲📝 [X] points, keep pioneering!",
	"Seven days, seven notes - you're a note-taking DJ, dropping beats of wisdom! 🎧📝 [X] points, keep spinning!",
	"You're on a seven-day note-taking treasure hunt, discovering gems of wisdom! 💎📝 [X] points, keep hunting!",
	"Seven days straight? You're the note-taking ninja warrior, conquering the knowledge obstacle course! 🥋📝 [X] points, keep slaying!",
	"You're on a seven-day note-taking rollercoaster! Up and down, but always moving forward! 🎢📝 [X] points, enjoy the ride!",
	"Seven days, seven notes - you're a note-taking DJ spinning knowledge beats! 🎧📝 [X] points, drop the knowledge!",
	"You've just conquered the seven-day note-taking challenge! You're the note-taking Indiana Jones! 🏹📝 [X] points, keep exploring!",
	"A whole week of notes? You're the note-taking Sherlock Holmes, solving knowledge mysteries! 🔍📝 [X] points, keep sleuthing!",
	"Seven days, seven notes - you're a note-taking Picasso, creating a masterpiece of knowledge! 🎨📝 [X] points, keep painting!",
	"You're on a seven-day note-taking safari, exploring the wilds of knowledge! 🐘📝 [X] points, keep exploring!",
	"Seven days straight? You're the Tony Hawk of note-taking! 🛹📝 [X] points, keep shredding!",
	"You're on a seven-day note-taking rocket ship! Destination: Infinite Knowledge! 🚀📝 [X] points, enjoy the journey!",
	"Seven days, seven notes - you're a note-taking ninja turtle now! 🐢📝 [X] points, cowabunga!",
	"You've just completed a week-long note-taking marathon! 🏃‍♂️📝 [X] points earned. Ready for the next lap?",
	"A whole week of notes? You're on fire! 🔥📝 [X] points, keep the spark alive!",
	"Seven notes in seven days - that's like a note symphony! 🎶📝 [X] points, maestro!"
];

const twoNoteMessages: string[] = [
	"Boom! You just aced the 2-note tango! 🎉 [X] points in the pocket. Keep groovin'!",
	"Two notes in a day? You're officially a Note Ninja! 🥋 [X] points earned. Rock on!",
	"High-five! You've conquered the 2-note rodeo! 🤠 [X] points earned. Yeehaw!",
	"Double trouble! Two notes in one day, you legend! 🌟 [X] points, rockstar!",
	"You're on fire! Two notes in a day - what's your secret weapon? 🔥 [X] points!",
	"Bingo! Two notes in a day! You're on a roll! 🚀 [X] points earned. Keep it up!",
	"Kaboom! You just blew the 2-note challenge out of the water! 💥 [X] points!",
	"You're officially a 2-note superstar! 🌟 [X] points in the bag. Keep shining!",
	"Double up, double down! Two notes in one day - you're a rockstar! 🎸 [X] points!",
	"You've just joined the 2-note party! 🥳 [X] points earned. Let's keep dancing!",
	"Ka-ching! Two notes in a day! You're racking up those points! 💰 [X] earned!",
	"You're a 2-note magician! 🎩✨ [X] points earned. What's your next trick?",
	"Two notes? Nailed it! You're on a roll! 🌟 [X] points earned. Keep it going!",
	"Abra-cadabra! Two notes appear! 🎩✨ [X] points earned. Keep the magic alive!",
	"Double trouble, double the fun! Two notes in one day! 🎉 [X] points, superstar!",
	"You've just unlocked the 2-note achievement! 🌟 [X] points earned. Keep soaring!",
	"Woo-hoo! Two notes in a day! You're on fire! 🔥 [X] points, keep it up!",
	"You're a 2-note wizard! ✨🔮 [X] points earned. What's your next spell?",
	"Double the notes, double the awesomeness! 🌟 [X] points, rockstar!",
	"You've just kicked the 2-note challenge out of the park! ⚾ [X] points!",
	"Boom! You just conquered the 2-note challenge! 🎉 [X] points, superstar!",
	"Double the notes, double the celebration! 🥳 [X] points earned. Party on!",
	"You're a 2-note maestro! 🎵 [X] points in the pocket. Keep the music playing!",
	"Kaboom! Two notes in a day! You're on a roll! 🚀 [X] points earned. Keep it up!",
	"You've just joined the 2-note fiesta! 🥳 [X] points earned. Let's keep dancing!",
	"Zap! You've just electrified the 2-note challenge! ⚡ [X] points, rockstar!",
	"Double notes, double the sparkle! 🌟 [X] points earned. Keep shining bright!",
	"You're a 2-note dynamo! 💥 [X] points earned. What's your next explosion?",
	"Kaboom! Two notes in a day! You're on fire! 🔥 [X] points, keep it up!",
	"You've just unlocked the 2-note achievement! 🌟 [X] points earned. Keep soaring!",
	"Woo-hoo! Two notes in a day! You're on a roll! 🎉 [X] points, keep it up!",
	"You're a 2-note wizard! ✨🔮 [X] points earned. What's your next spell?",
	"Double the notes, double the awesomeness! 🌟 [X] points, rockstar!",
	"You've just kicked the 2-note challenge out of the park! ⚾ [X] points!",
	"Boom! You just conquered the 2-note challenge! 🎉 [X] points, superstar!",
	"Double the notes, double the celebration! 🥳 [X] points earned. Party on!",
	"You're a 2-note maestro! 🎵 [X] points in the pocket. Keep the music playing!",
	"Zap! You've just electrified the 2-note challenge! ⚡ [X] points, rockstar!",
	"Double notes, double the sparkle! 🌟 [X] points earned. Keep shining bright!",
	"You're a 2-note dynamo! 💥 [X] points earned. What's your next explosion?",
	"Kapow! Two notes in a day - you're a superhero! 🦸‍♂️ [X] points!",
	"You're a 2-note legend! 🌟 [X] points earned. What's your next adventure?",
	"Bingo! Two notes in a day! You're on a roll! 🚀 [X] points, keep it up!",
	"You're a 2-note wizard! ✨🔮 [X] points earned. What's your next spell?",
	"Double the notes, double the awesomeness! 🌟 [X] points, rockstar!",
	"You've just kicked the 2-note challenge out of the park! ⚾ [X] points!",
	"Boom! You just conquered the 2-note challenge! 🎉 [X] points, superstar!",
	"Double the notes, double the celebration! 🥳 [X] points earned. Party on!",
	"You're a 2-note maestro! 🎵 [X] points in the pocket. Keep the music playing!",
	"Zap! You've just electrified the 2-note challenge! ⚡ [X] points, rockstar!",
	"Double notes, double the sparkle! 🌟 [X] points earned. Keep shining bright!",
	"You're a 2-note dynamo! 💥 [X] points earned. What's your next explosion?"
];

const randomPointNotices: string[] = [
	"Bazinga! You just snagged [X] points!",
	"Kaboom! [X] points are now in your pocket!",
	"Woohoo! [X] points earned! Keep it up!",
	"Points ahoy! [X] more in the bank!",
	"Score! [X] points added to your total!",
	"You're on fire! [X] points in the bag!",
	"Zippity-zap! [X] points for you!",
	"Champion move! [X] points are yours!",
	"Bingo! [X] points just for you!",
	"Shazam! [X] points to the rescue!",
	"Ka-ching! [X] points earned!",
	"Superb! [X] more points for you!",
	"Bravo! [X] points added to your stash!",
	"Well done! [X] more points in tow!",
	"Zap! [X] points, just like that!",
	"A round of applause for [X] points!",
	"Whoosh! [X] points are yours!",
	"Zing! [X] points for your efforts!",
	"Woo! [X] points, way to go!",
	"Zesty! [X] points in your tally!",
	"Great job! [X] more points for you!",
	"Fantastic! [X] points in the bag!",
	"Zowie! [X] points just for you!",
	"Hooray! [X] points in your account!",
	"Nice one! [X] points in the pocket!",
	"Woot woot! [X] points, nice work!",
	"Zigzag! [X] points, keep it up!",
	"Bam! [X] points, well done!",
	"Cool beans! [X] points for you!",
	"Zesty! [X] points, keep it up!",
	"Splendid! [X] points for your efforts!",
	"Marvelous! [X] points earned!",
	"Zany! [X] points, well done!",
	"Exquisite! [X] points in your stash!",
	"Outstanding! [X] points for you!",
	"Zesty! [X] points, nice job!",
	"Magnificent! [X] points earned!",
	"Zigzag! [X] points in your tally!",
	"Terrific! [X] points for you!",
	"Superb! [X] points, well done!",
	"Zowie! [X] points for your efforts!",
	"Excellent! [X] points earned!",
	"Zap! [X] points in your account!",
	"Awesome! [X] points, way to go!",
	"Well played! [X] points for you!",
	"Zesty! [X] points, nice work!",
	"Impressive! [X] points, keep it up!",
	"Brilliant! [X] points, well done!",
	"Zing! [X] points for your efforts!",
	"Nice move! [X] points earned!",
	"Zesty! [X] points in the bag!",
	"Stellar! [X] points just for you!",
	"Well deserved! [X] points earned!"
];

const boosterFactorMessage : string[] = [
	"Boom! You just hit a new Boosterfactor milestone! High five, booster pro!",
	"Boosting it up! High five for reaching that Boosterfactor benchmark!",
	"Way to amplify your game! High five for hitting that Boosterfactor goal!",
	"You're turbocharging your progress! High five for achieving that Boosterfactor milestone!",
	"Bam! Another Boosterfactor milestone smashed! High five, booster champion!",
	"You're on turbo mode! High five for maximizing your Boosterfactor!",
	"High five alert! You just boosted your way to a new milestone!",
	"You're officially a booster master! High five for your unstoppable Boosterfactor streak!",
	"Nailed it! High five for reaching another Boosterfactor milestone!",
	"Woo hoo! High five for leveling up your Boosterfactor game!",
	"On a boost spree! High five for maximizing your Boosterfactor!",
	"High fives all around for reaching that Boosterfactor milestone!",
	"Look at you go! High five for turbocharging your Boosterfactor!",
	"You're making waves with your Boosterfactor! High five for the milestone!",
	"High five incoming! You're a Boosterfactor maestro!",
	"Keep 'em coming! High five for reaching another Boosterfactor milestone!",
	"Bravo! High five for your stellar Boosterfactor progress!",
	"High fives galore for hitting that Boosterfactor milestone!",
	"You're unstoppable! High five for your Boosterfactor mayhem!",
	"Kaboom! High five for blowing past that Boosterfactor milestone!",
	"Way to hustle with your Boosterfactor! High five, booster hustler!",
	"High five vibes for boosting your way to that milestone!",
	"Bringing the heat with your Boosterfactor! High five for the milestone heatwave!",
	"You're a Boosterfactor machine! High five, keep it up!",
	"High fives incoming! You're a Boosterfactor mastermind!",
	"Boosting like a boss! High five, booster superstar!",
	"Look out, world! High five for your Boosterfactor domination!",
	"High fives on repeat! You're a Boosterfactor magician!",
	"Impressive stuff! High five for your Boosterfactor magic!",
	"You're unstoppable! High five for your Boosterfactor momentum!",
	"Keep the boost alive! High five for your Boosterfactor mojo!",
	"High fives are in order! You're a Boosterfactor ninja!",
	"Mission accomplished! High five for reaching that Boosterfactor milestone!",
	"You're on a boost roll! High five for your Boosterfactor rampage!",
	"High five alert! You're a Boosterfactor rockstar!",
	"Two thumbs up! High five for your Boosterfactor success!",
	"You're boosting it! High five for your Boosterfactor spree!",
	"High fives incoming! You're a Boosterfactor sensation!",
	"You're a Boosterfactor superhero! High five, booster caped crusader!",
	"High five vibes! You're a Boosterfactor sensation!",
	"You're a Boosterfactor legend! High five, oh mighty booster!",
	"High fives all around! You're a Boosterfactor superstar!",
	"You're a Boosterfactor champion! High five, boost conqueror!",
	"High five incoming! You're a Boosterfactor warrior!",
	"You're on fire with your Boosterfactor! High five for the victory!",
	"You're a Boosterfactor guru! High five, wise booster!",
	"High five vibes! You're a Boosterfactor wizard!",
	"You're a Boosterfactor icon! High five, illustrious booster!",
	"High five alert! You're a Boosterfactor prodigy!",
	"You're unstoppable! High five for your Boosterfactor triumph!"
]

export function getRandomMessageWeeklyChallenge(points: number): string {
	const randomIndex = Math.floor(Math.random() * messagesWeeklyChallenge.length);
	const message = messagesWeeklyChallenge[randomIndex];
	return message.replace("[X]", Math.round(points).toString());
}


export function getRandomMessageTwoNoteChallenge(points: number): string {
	const randomIndex = Math.floor(Math.random() * twoNoteMessages.length);
	const message = twoNoteMessages[randomIndex];
	return message.replace("[X]", Math.round(points).toString());
}


export function getRandomMessagePoints(points: number): string {
	const randomIndex = Math.floor(Math.random() * randomPointNotices.length);
	const message = randomPointNotices[randomIndex];
	return message.replace("[X]", Math.round(points).toString());
}

export function getRandomMessageBoosterFactor(): string {
	const randomIndex = Math.floor(Math.random() * boosterFactorMessage.length);
	return boosterFactorMessage[randomIndex];
}

// Example usage
// const randomPoints = 100; // Replace with your actual points value
// const randomMessage = getRandomMessageWeeklyChallenge(randomPoints);
// console.debug(randomMessage);


